# Generated by Django 3.1.2 on 2020-10-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(verbose_name='date published')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
