# Generated by Django 3.1.2 on 2020-10-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='location',
            field=models.TextField(max_length=100),
        ),
    ]
