# Generated by Django 3.1.2 on 2020-10-25 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_auto_20201025_1012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Order',
        ),
    ]
