# Generated by Django 3.1.2 on 2020-10-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_auto_20201025_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
