# Generated by Django 3.1.2 on 2020-10-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0008_auto_20201025_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmail',
            name='User_email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
